
package pos.system;

import dao.DatabaseConnect;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Customer extends javax.swing.JPanel {

    /**
     * Creates new form Customer
     */
    private String name;
    private String tel;
    private int id;
        
    public Customer() {
        
        initComponents();
        table_load();
        addPlaceholder(cust_name, "Enter customer name");
        addPlaceholder(cust_tel, "Enter phone no. (10-11 digit only)");
    }

    public void table_load() {

        try {

            DefaultTableModel dt = (DefaultTableModel)cust_show_table.getModel();
            dt.setRowCount(0);

            Statement s = DatabaseConnect.dbconn().createStatement();

            ResultSet result = s.executeQuery(" SELECT * FROM customer");

            while (result.next()) {

                Vector v = new Vector();

                v.add(result.getString(1));
                v.add(result.getString(2));
                v.add(result.getString(3));

                dt.addRow(v);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cust_save_btn = new javax.swing.JButton();
        cust_search_btn = new javax.swing.JButton();
        cust_update_btn = new javax.swing.JButton();
        cust_delete_btn = new javax.swing.JButton();
        cust_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cust_tel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cust_show_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cust_search = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cust_search_table = new javax.swing.JTextField();

        jButton2.setText("Save");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        jPanel1.setPreferredSize(new java.awt.Dimension(451, 244));

        cust_save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/save.png"))); // NOI18N
        cust_save_btn.setText("Save");
        cust_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_save_btnActionPerformed(evt);
            }
        });

        cust_search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/search x30.png"))); // NOI18N
        cust_search_btn.setText("Search");
        cust_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_search_btnActionPerformed(evt);
            }
        });

        cust_update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/update.png"))); // NOI18N
        cust_update_btn.setText("Update");
        cust_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_update_btnActionPerformed(evt);
            }
        });

        cust_delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/delete.png"))); // NOI18N
        cust_delete_btn.setText("Delete");
        cust_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_delete_btnActionPerformed(evt);
            }
        });

        cust_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cust_name.setMinimumSize(new java.awt.Dimension(64, 23));
        cust_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cust_nameFocusGained(evt);
            }
        });
        cust_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_nameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tel. Num:");

        cust_tel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cust_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_telActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cust_save_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cust_search_btn)
                .addGap(18, 18, 18)
                .addComponent(cust_update_btn)
                .addGap(18, 18, 18)
                .addComponent(cust_delete_btn)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cust_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cust_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cust_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cust_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cust_save_btn)
                    .addComponent(cust_delete_btn)
                    .addComponent(cust_search_btn)
                    .addComponent(cust_update_btn))
                .addGap(37, 37, 37))
        );

        cust_show_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cust_show_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Customer Name", "PH Number"
            }
        ));
        cust_show_table.setRowHeight(23);
        cust_show_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cust_show_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cust_show_table);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        jPanel2.setPreferredSize(new java.awt.Dimension(463, 108));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer info:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Search ID:");

        cust_search.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cust_search.setToolTipText("Enter ID");
        cust_search.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(cust_search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cust_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(110, 89, 222));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Customer Information Management");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Administration / Customer Panel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Search:");

        cust_search_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cust_search_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_search_tableActionPerformed(evt);
            }
        });
        cust_search_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cust_search_tableKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cust_search_table, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cust_search_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void search_data(int id) {
        
        //get the id enter in the text field
        
        try {
            Statement s = DatabaseConnect.dbconn().createStatement();
            //Fetch customer data that match the id entered from DATABASE
            ResultSet result = s.executeQuery(" SELECT * FROM customer WHERE cust_id = " + id + "");
            //if data exist, show data on text field
            if (result.next()) {
                cust_name.setText(result.getString("cust_name"));
                cust_tel.setText(result.getString("cust_tel"));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        table_load();
    }
    
    public void search_data(String search) {
        
        // search customer table
        name = cust_search_table.getText();
        tel = cust_search_table.getText();
        
        try {

            DefaultTableModel dt = (DefaultTableModel)cust_show_table.getModel();
            dt.setRowCount(0);
            
            Statement s = DatabaseConnect.dbconn().createStatement();

            ResultSet result = s.executeQuery(" SELECT * FROM customer WHERE cust_name LIKE '%" + name + "%' OR cust_tel LIKE '%" + tel + "%'");

            while (result.next()) {

                Vector v = new Vector();

                v.add(result.getString(1));
                v.add(result.getString(2));
                v.add(result.getString(3));

                dt.addRow(v);
            }
        } catch (SQLException e) {
            table_load();
        }
    }
    
    public void save_data() {
        
        //get the data enter in the text field
        name = cust_name.getText();
        tel = cust_tel.getText();

        try {
            Statement s = DatabaseConnect.dbconn().createStatement();
            
            // Save the customer data in DATABASE
            s.executeUpdate(" INSERT INTO customer (cust_name, cust_tel) VALUES ('" + name + "','" + tel + "')");
            JOptionPane.showMessageDialog(null, "Data Saved.");
            
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        table_load();
    }
    
    public void update_data() {
        
        // Get the data enter in the text field
        name = cust_name.getText();
        tel = cust_tel.getText();
        id = (int)cust_search.getValue();

        try {
            Statement s = DatabaseConnect.dbconn().createStatement();
            // Update the customer data in DATABASE based on the id entered
            s.executeUpdate(" UPDATE customer SET cust_name = '" + name + "' , cust_tel = '" + tel + "' WHERE cust_id = " + id + "");
            JOptionPane.showMessageDialog(null, "Data Updated.");
            
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        table_load();
    }
    
    public void delete_data() {
        
        // Get the data enter in the text field
        id = (int)cust_search.getValue();

        try {
            Statement s = DatabaseConnect.dbconn().createStatement();
            // Delete the customer data in DATABASE based on the id entered
            s.executeUpdate(" DELETE FROM customer WHERE cust_id = '" + id + "'");
            JOptionPane.showMessageDialog(null, "Data Deleted.");
            
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        table_load();
    }
    
    private void cust_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_search_btnActionPerformed
        // search button function
        search_data((int)cust_search.getValue());
        
    }//GEN-LAST:event_cust_search_btnActionPerformed
    
    // Custom method to add placeholder text when the JTextField is empty and loses focus
    private void addPlaceholder(javax.swing.JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(Color.GRAY);

        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(Color.GRAY);
                }
            }
        });
    }
    
    private void cust_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_nameActionPerformed
        
    }//GEN-LAST:event_cust_nameActionPerformed

    private void cust_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_telActionPerformed
        
    }//GEN-LAST:event_cust_telActionPerformed

    private void cust_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_save_btnActionPerformed
        // save customer data
        save_data();
        
    }//GEN-LAST:event_cust_save_btnActionPerformed

    private void cust_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_update_btnActionPerformed
        // update customer data
        update_data();
        
    }//GEN-LAST:event_cust_update_btnActionPerformed

    private void cust_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_delete_btnActionPerformed
        // delete customer data
        delete_data();
        
    }//GEN-LAST:event_cust_delete_btnActionPerformed

    private void cust_show_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cust_show_tableMouseClicked
        // mouse click and show data on textfield
        
        int r = cust_show_table.getSelectedRow();
        
        id = Integer.parseInt((String)cust_show_table.getValueAt(r, 0));
        name = cust_show_table.getValueAt(r, 1).toString();
        tel = cust_show_table.getValueAt(r, 2).toString();
        
        cust_search.setValue(id);
        cust_name.setText(name);
        cust_tel.setText(tel);
        
        
    }//GEN-LAST:event_cust_show_tableMouseClicked

    private void cust_search_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cust_search_tableKeyReleased
        search_data(cust_search_table.getText());
    }//GEN-LAST:event_cust_search_tableKeyReleased

    private void cust_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cust_nameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_nameFocusGained

    private void cust_search_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_search_tableActionPerformed
        addPlaceholder(cust_name, "Enter name to search");
    }//GEN-LAST:event_cust_search_tableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cust_delete_btn;
    private javax.swing.JTextField cust_name;
    private javax.swing.JButton cust_save_btn;
    private javax.swing.JSpinner cust_search;
    private javax.swing.JButton cust_search_btn;
    private javax.swing.JTextField cust_search_table;
    private javax.swing.JTable cust_show_table;
    private javax.swing.JTextField cust_tel;
    private javax.swing.JButton cust_update_btn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
