
package pos.system;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {
    JpanelLoader jpload = new JpanelLoader();
    private boolean isButtonClicked = false;
    private String email;
    
    public Home() {
        initComponents();
        this.setExtendedState(Home.MAXIMIZED_BOTH);
        applyHoverEffectToButtonGroup(Home_btn_grp);
    }
    
    public Home(String userEmail) {
        initComponents();
        email = userEmail;
        if (email.equals("admin@gmail.com")) {
//            categoryBtn.setVisible(false);
//            newProductBtn.setVisible(false);
//            viewEditDeleteBtn.setVisible(false);
//            verifyUser.setVisible(false);
            
        }
        this.setExtendedState(Home.MAXIMIZED_BOTH);
        applyHoverEffectToButtonGroup(Home_btn_grp);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home_btn_grp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        employeeBtn = new javax.swing.JToggleButton();
        customerBtn = new javax.swing.JToggleButton();
        categoryBtn = new javax.swing.JToggleButton();
        productVBtn = new javax.swing.JToggleButton();
        invoiceBtn = new javax.swing.JToggleButton();
        reportBtn = new javax.swing.JToggleButton();
        logoutBtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        exitBtn = new javax.swing.JToggleButton();
        load_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        employeeBtn.setBackground(new java.awt.Color(54, 33, 89));
        Home_btn_grp.add(employeeBtn);
        employeeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        employeeBtn.setForeground(new java.awt.Color(204, 204, 204));
        employeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/employee.png"))); // NOI18N
        employeeBtn.setText("Users");
        employeeBtn.setBorder(null);
        employeeBtn.setBorderPainted(false);
        employeeBtn.setFocusPainted(false);
        employeeBtn.setIconTextGap(6);
        employeeBtn.setPreferredSize(new java.awt.Dimension(70, 20));
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });

        customerBtn.setBackground(new java.awt.Color(54, 33, 89));
        Home_btn_grp.add(customerBtn);
        customerBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerBtn.setForeground(new java.awt.Color(204, 204, 204));
        customerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/customer.png"))); // NOI18N
        customerBtn.setText("Customer");
        customerBtn.setBorder(null);
        customerBtn.setFocusPainted(false);
        customerBtn.setIconTextGap(6);
        customerBtn.setPreferredSize(new java.awt.Dimension(70, 20));
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        categoryBtn.setBackground(new java.awt.Color(54, 33, 89));
        Home_btn_grp.add(categoryBtn);
        categoryBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        categoryBtn.setForeground(new java.awt.Color(204, 204, 204));
        categoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/menu.png"))); // NOI18N
        categoryBtn.setText("Category");
        categoryBtn.setBorder(null);
        categoryBtn.setBorderPainted(false);
        categoryBtn.setFocusPainted(false);
        categoryBtn.setPreferredSize(new java.awt.Dimension(70, 20));
        categoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryBtnActionPerformed(evt);
            }
        });

        productVBtn.setBackground(new java.awt.Color(54, 33, 89));
        Home_btn_grp.add(productVBtn);
        productVBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productVBtn.setForeground(new java.awt.Color(204, 204, 204));
        productVBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/running-shoe.png"))); // NOI18N
        productVBtn.setText("Product");
        productVBtn.setBorder(null);
        productVBtn.setBorderPainted(false);
        productVBtn.setFocusPainted(false);
        productVBtn.setIconTextGap(8);
        productVBtn.setPreferredSize(new java.awt.Dimension(70, 20));
        productVBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productVBtnActionPerformed(evt);
            }
        });

        invoiceBtn.setBackground(new java.awt.Color(54, 33, 89));
        Home_btn_grp.add(invoiceBtn);
        invoiceBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        invoiceBtn.setForeground(new java.awt.Color(204, 204, 204));
        invoiceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/bill_1.png"))); // NOI18N
        invoiceBtn.setText("Invoice");
        invoiceBtn.setBorder(null);
        invoiceBtn.setBorderPainted(false);
        invoiceBtn.setFocusPainted(false);
        invoiceBtn.setIconTextGap(8);
        invoiceBtn.setPreferredSize(new java.awt.Dimension(70, 20));
        invoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceBtnActionPerformed(evt);
            }
        });

        reportBtn.setBackground(new java.awt.Color(54, 33, 89));
        Home_btn_grp.add(reportBtn);
        reportBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportBtn.setForeground(new java.awt.Color(204, 204, 204));
        reportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/analysis.png"))); // NOI18N
        reportBtn.setText("Report");
        reportBtn.setBorder(null);
        reportBtn.setBorderPainted(false);
        reportBtn.setFocusPainted(false);
        reportBtn.setIconTextGap(8);
        reportBtn.setPreferredSize(new java.awt.Dimension(70, 20));
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(102, 0, 204));
        Home_btn_grp.add(logoutBtn);
        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(204, 204, 204));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/check-out.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setFocusPainted(false);
        logoutBtn.setFocusable(false);
        logoutBtn.setIconTextGap(8);
        logoutBtn.setPreferredSize(new java.awt.Dimension(70, 20));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Adidas");

        jSeparator1.setForeground(new java.awt.Color(230, 230, 230));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 12));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 12));

        exitBtn.setBackground(new java.awt.Color(102, 0, 204));
        Home_btn_grp.add(exitBtn);
        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(204, 204, 204));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/logout.png"))); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setBorder(null);
        exitBtn.setContentAreaFilled(false);
        exitBtn.setFocusPainted(false);
        exitBtn.setFocusable(false);
        exitBtn.setIconTextGap(8);
        exitBtn.setPreferredSize(new java.awt.Dimension(70, 20));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(reportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoiceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productVBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(employeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(categoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productVBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(invoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {categoryBtn, customerBtn, employeeBtn, invoiceBtn, logoutBtn, productVBtn, reportBtn});

        jSeparator1.getAccessibleContext().setAccessibleName("");

        load_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout load_panelLayout = new javax.swing.GroupLayout(load_panel);
        load_panel.setLayout(load_panelLayout);
        load_panelLayout.setHorizontalGroup(
            load_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        load_panelLayout.setVerticalGroup(
            load_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(load_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(load_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportBtnActionPerformed

    private void invoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceBtnActionPerformed

    private void productVBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productVBtnActionPerformed
        //load product info
        ManageProduct mgpd = new ManageProduct();
        jpload.jPanelLoader(load_panel, mgpd);
    }//GEN-LAST:event_productVBtnActionPerformed

    private void categoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryBtnActionPerformed
        //load category info
        ManageCategory mgct = new ManageCategory();
        jpload.jPanelLoader(load_panel, mgct);

    }//GEN-LAST:event_categoryBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        //load customer info
        Customer cust = new Customer();
        jpload.jPanelLoader(load_panel, cust);

        
    }//GEN-LAST:event_customerBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        //load employee info
        ManageUser emp = new ManageUser();
        jpload.jPanelLoader(load_panel, emp);
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1PropertyChange

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you sure to Close The Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed
    
    // method to design hover and click effect on the buttons in  Home_btn_grp
    private void applyHoverEffect(AbstractButton button) {
    Color color = new Color(54, 33, 89);
    Color hoverColor = new Color(153, 153, 255);
    
    button.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent evt) {
            if (!isButtonClicked) {
                button.setBackground(hoverColor);
                button.repaint(); // Make sure to repaint the button
            }
        }

        @Override
        public void mouseExited(MouseEvent evt) {
            if (!isButtonClicked) {
                button.setBackground(color);
                button.repaint(); // Make sure to repaint the button
            }
        }
    });

    button.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evt) {
            isButtonClicked = true;
            button.setBackground(hoverColor);
            button.repaint(); // Make sure to repaint the button
        }
    });

    button.addFocusListener(new FocusAdapter() {
        @Override
        public void focusLost(FocusEvent evt) {
            if (isButtonClicked) {
                button.setBackground(color);
                button.repaint(); // Make sure to repaint the button
            }
        }
    });
}

private void applyHoverEffectToButtonGroup(ButtonGroup buttonGroup) {
    Enumeration<AbstractButton> buttons = buttonGroup.getElements();
    while (buttons.hasMoreElements()) {
        AbstractButton button = buttons.nextElement();
        applyHoverEffect(button);
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Home_btn_grp;
    private javax.swing.JToggleButton categoryBtn;
    private javax.swing.JToggleButton customerBtn;
    private javax.swing.JToggleButton employeeBtn;
    private javax.swing.JToggleButton exitBtn;
    private javax.swing.JToggleButton invoiceBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel load_panel;
    private javax.swing.JToggleButton logoutBtn;
    private javax.swing.JToggleButton productVBtn;
    private javax.swing.JToggleButton reportBtn;
    // End of variables declaration//GEN-END:variables
}
