package pos.system;

import dao.CategoryDao;
import dao.DatabaseConnect;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;

public class ManageCategory extends javax.swing.JPanel {

    /**
     * Creates new form Customer
     */

    public ManageCategory() {

        initComponents();

        table_load();
        addPlaceholder(category_txt, "Enter category name");
        cat_save_btn.setEnabled(false);
        cat_delete_btn.setEnabled(false);
        cat_update_btn.setEnabled(false);
    }

    private void table_load() {
        DefaultTableModel dtm = (DefaultTableModel) cat_show_table.getModel();
        dtm.setRowCount(0);
        ArrayList<Category> list = CategoryDao.getAllRecords();
        for (Category categoryObj : list) {
            dtm.addRow(new Object[]{categoryObj.getId(), categoryObj.getName()});
        }
    }

    public void validateField() {
        String category = category_txt.getText().trim();
        if (!category.isEmpty() && !category.equals("Enter category name")) {
            cat_save_btn.setEnabled(true);
            cat_delete_btn.setEnabled(true);
            cat_update_btn.setEnabled(true);
        } else {
            cat_save_btn.setEnabled(false);
            cat_delete_btn.setEnabled(false);
            cat_update_btn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cat_save_btn = new javax.swing.JButton();
        cat_update_btn = new javax.swing.JButton();
        cat_delete_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        category_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cat_show_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cat_search = new javax.swing.JSpinner();
        cat_search_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cat_search_table = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("Save");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        jPanel1.setPreferredSize(new java.awt.Dimension(451, 244));

        cat_save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/save.png"))); // NOI18N
        cat_save_btn.setText("Save");
        cat_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_save_btnActionPerformed(evt);
            }
        });

        cat_update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/update.png"))); // NOI18N
        cat_update_btn.setText("Update");
        cat_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_update_btnActionPerformed(evt);
            }
        });

        cat_delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/delete.png"))); // NOI18N
        cat_delete_btn.setText("Delete");
        cat_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_delete_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category:");

        category_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                category_txtFocusLost(evt);
            }
        });
        category_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_txtActionPerformed(evt);
            }
        });
        category_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                category_txtKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add/Edit/Delete category info:");

        clearBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setPreferredSize(new java.awt.Dimension(92, 30));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cat_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cat_update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cat_delete_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(category_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(category_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cat_save_btn)
                    .addComponent(cat_update_btn)
                    .addComponent(cat_delete_btn)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 480, 230));

        cat_show_table.setBackground(new java.awt.Color(153, 255, 153));
        cat_show_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cat_show_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category"
            }
        ));
        cat_show_table.setRowHeight(23);
        cat_show_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cat_show_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cat_show_table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 549, 340));

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        jPanel2.setPreferredSize(new java.awt.Dimension(463, 108));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search category info:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search ID:");

        cat_search.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cat_search.setToolTipText("Enter ID");
        cat_search.setBorder(null);

        cat_search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/search x30.png"))); // NOI18N
        cat_search_btn.setText("Search");
        cat_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(cat_search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cat_search_btn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cat_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cat_search_btn))
                .addGap(13, 13, 13))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 480, -1));

        jPanel3.setBackground(new java.awt.Color(43, 99, 63));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Product Category Management");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Administration / Category Panel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(730, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cat_search_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cat_search_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_search_tableActionPerformed(evt);
            }
        });
        cat_search_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cat_search_tableKeyReleased(evt);
            }
        });
        add(cat_search_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/background.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -20, 1400, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void search_data(String search) {

        // search customer table
        String name = cat_search_table.getText();

        try {

            DefaultTableModel dt = (DefaultTableModel) cat_show_table.getModel();
            dt.setRowCount(0);

            Statement s = DatabaseConnect.dbconn().createStatement();

            ResultSet result = s.executeQuery(" SELECT * FROM category WHERE category_name LIKE '%" + name + "%'");

            while (result.next()) {

                Vector v = new Vector();

                v.add(result.getString(1));
                v.add(result.getString(2));

                dt.addRow(v);
            }
        } catch (SQLException e) {

        }
    }


    private void cat_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_search_btnActionPerformed
        // search button function
        Category category = new Category();
        String id = cat_search.getValue().toString();
        category = CategoryDao.searchRecord(id);
        if (category != null) {
            category_txt.setText(category.getName());
        }
        validateField();
    }//GEN-LAST:event_cat_search_btnActionPerformed

    // Custom method to add placeholder text when the JTextField is empty and loses focus
    private void addPlaceholder(javax.swing.JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(Color.GRAY);

        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(Color.GRAY);
                }
            }
        });
    }

    private void category_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_txtActionPerformed

    }//GEN-LAST:event_category_txtActionPerformed

    private void cat_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_save_btnActionPerformed
        // Save category data

        String categoryName = category_txt.getText();
        
        try {
            Category category = CategoryDao.checkRecord(categoryName);

            if (category == null) {
                category = new Category();
                category.setName(categoryName);
                CategoryDao.saveCategory(category);
            } else {
                ImageIcon icon = new ImageIcon("src/pos/system/img/delete.png");
                JOptionPane.showMessageDialog(null, "<html><b style=\"font-size: larger\">This category already exist!</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ManageCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
        table_load();
    }//GEN-LAST:event_cat_save_btnActionPerformed

    private void cat_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_update_btnActionPerformed
        // update customer data
        String id = cat_search.getValue().toString();
        Category category = new Category();
        category.setId((String) cat_search.getValue());
        category.setName(category_txt.getText());
        try {
            CategoryDao.updateCategory(category);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
        table_load();
    }//GEN-LAST:event_cat_update_btnActionPerformed

    private void cat_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_delete_btnActionPerformed
        // delete customer data
        Category category = new Category();
        String id = cat_search.getValue().toString();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Delete " + category.getName() + " Category?", "Select", JOptionPane.YES_NO_OPTION);

        try {
            if (a == 0) {
                CategoryDao.deleteCategory(id);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
        table_load();
    }//GEN-LAST:event_cat_delete_btnActionPerformed

    private void cat_show_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cat_show_tableMouseClicked
        // mouse click and show data on textfield

        int index = cat_show_table.getSelectedRow();
        TableModel model = cat_show_table.getModel();
        String id = model.getValueAt(index, 0).toString();
        String name = model.getValueAt(index, 1).toString();

        cat_search.setValue(Integer.valueOf(id));
        category_txt.setText(name);
        validateField();
    }//GEN-LAST:event_cat_show_tableMouseClicked

    private void cat_search_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cat_search_tableKeyReleased
        search_data(cat_search_table.getText());
    }//GEN-LAST:event_cat_search_tableKeyReleased

    private void cat_search_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_search_tableActionPerformed
        addPlaceholder(cat_search_table, "Enter name to search");
    }//GEN-LAST:event_cat_search_tableActionPerformed

    private void category_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_category_txtKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_category_txtKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here: 
    }//GEN-LAST:event_formComponentShown


    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        category_txt.setText("");
        validateField();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void category_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_category_txtFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_category_txtFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cat_delete_btn;
    private javax.swing.JButton cat_save_btn;
    private javax.swing.JSpinner cat_search;
    private javax.swing.JButton cat_search_btn;
    private javax.swing.JTextField cat_search_table;
    private javax.swing.JTable cat_show_table;
    private javax.swing.JButton cat_update_btn;
    private javax.swing.JTextField category_txt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
