package pos.system;

import dao.CategoryDao;
import dao.DatabaseConnect;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;

public class ManageUser extends javax.swing.JPanel {

    /**
     * Creates new form Customer
     */

    public ManageUser() {

        initComponents();

        
        addPlaceholder(category_txt, "Enter category name");
        cat_save_btn.setEnabled(false);
        cat_delete_btn.setEnabled(false);
        cat_update_btn.setEnabled(false);
    }

    

    public void validateField() {
        String category = category_txt.getText().trim();
        if (!category.isEmpty() && !category.equals("Enter category name")) {
            cat_save_btn.setEnabled(true);
            cat_delete_btn.setEnabled(true);
            cat_update_btn.setEnabled(true);
        } else {
            cat_save_btn.setEnabled(false);
            cat_delete_btn.setEnabled(false);
            cat_update_btn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cat_save_btn = new javax.swing.JButton();
        cat_update_btn = new javax.swing.JButton();
        cat_delete_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        category_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        category_txt1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        category_txt2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        category_txt3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        category_txt4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cat_search = new javax.swing.JSpinner();
        cat_search_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("Save");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        jPanel1.setPreferredSize(new java.awt.Dimension(451, 244));

        cat_save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/save.png"))); // NOI18N
        cat_save_btn.setText("Save");
        cat_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_save_btnActionPerformed(evt);
            }
        });

        cat_update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/update.png"))); // NOI18N
        cat_update_btn.setText("Update");
        cat_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_update_btnActionPerformed(evt);
            }
        });

        cat_delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/delete.png"))); // NOI18N
        cat_delete_btn.setText("Delete");
        cat_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_delete_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        category_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                category_txtFocusLost(evt);
            }
        });
        category_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_txtActionPerformed(evt);
            }
        });
        category_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                category_txtKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add/Edit/Delete user info:");

        clearBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setPreferredSize(new java.awt.Dimension(92, 30));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email:");

        category_txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category_txt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                category_txt1FocusLost(evt);
            }
        });
        category_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_txt1ActionPerformed(evt);
            }
        });
        category_txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                category_txt1KeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tel No:");

        category_txt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category_txt2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                category_txt2FocusLost(evt);
            }
        });
        category_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_txt2ActionPerformed(evt);
            }
        });
        category_txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                category_txt2KeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address:");

        category_txt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category_txt3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                category_txt3FocusLost(evt);
            }
        });
        category_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_txt3ActionPerformed(evt);
            }
        });
        category_txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                category_txt3KeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Security Question:");

        category_txt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category_txt4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                category_txt4FocusLost(evt);
            }
        });
        category_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_txt4ActionPerformed(evt);
            }
        });
        category_txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                category_txt4KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(category_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(category_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(category_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(category_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(category_txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 148, Short.MAX_VALUE)
                .addComponent(cat_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cat_update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cat_delete_btn)
                .addGap(144, 144, 144))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(category_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(category_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(category_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(category_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(category_txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cat_save_btn)
                    .addComponent(cat_update_btn)
                    .addComponent(cat_delete_btn)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 730, 330));

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        jPanel2.setPreferredSize(new java.awt.Dimension(463, 108));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search user info:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search ID:");

        cat_search.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cat_search.setToolTipText("Enter ID");
        cat_search.setBorder(null);

        cat_search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/search x30.png"))); // NOI18N
        cat_search_btn.setText("Search");
        cat_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(cat_search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cat_search_btn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cat_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cat_search_btn))
                .addGap(13, 13, 13))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 600, -1));

        jPanel3.setBackground(new java.awt.Color(43, 99, 63));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("User Management");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Administration / User Panel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(859, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/background.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -20, 1400, -1));
    }// </editor-fold>//GEN-END:initComponents

    


    private void cat_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_search_btnActionPerformed
        // search button function
        Category category = new Category();
        String id = cat_search.getValue().toString();
        category = CategoryDao.searchRecord(id);
        if (category != null) {
            category_txt.setText(category.getName());
        }
        validateField();
    }//GEN-LAST:event_cat_search_btnActionPerformed

    // Custom method to add placeholder text when the JTextField is empty and loses focus
    private void addPlaceholder(javax.swing.JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(Color.GRAY);

        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(Color.GRAY);
                }
            }
        });
    }

    private void category_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_txtActionPerformed

    }//GEN-LAST:event_category_txtActionPerformed

    private void cat_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_save_btnActionPerformed
        // Save category data

        String categoryName = category_txt.getText();
        
        try {
            Category category = CategoryDao.checkRecord(categoryName);

            if (category == null) {
                category = new Category();
                category.setName(categoryName);
                CategoryDao.saveCategory(category);
            } else {
                ImageIcon icon = new ImageIcon("src/pos/categoryNamesystem/img/delete.png");
                JOptionPane.showMessageDialog(null, "<html><b style=\"font-size: larger\">This category already exist!</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_cat_save_btnActionPerformed

    private void cat_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_update_btnActionPerformed
        // update customer data
        String id = cat_search.getValue().toString();
        Category category = new Category();
        category.setId((String) cat_search.getValue());
        category.setName(category_txt.getText());
        try {
            CategoryDao.updateCategory(category);
        } catch (SQLException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cat_update_btnActionPerformed

    private void cat_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_delete_btnActionPerformed
        // delete customer data
        Category category = new Category();
        String id = cat_search.getValue().toString();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Delete " + category.getName() + " Category?", "Select", JOptionPane.YES_NO_OPTION);

        try {
            if (a == 0) {
                CategoryDao.deleteCategory(id);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_cat_delete_btnActionPerformed

    private void category_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_category_txtKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_category_txtKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here: 
    }//GEN-LAST:event_formComponentShown


    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        category_txt.setText("");
        validateField();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void category_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_category_txtFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_category_txtFocusLost

    private void category_txt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_category_txt1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt1FocusLost

    private void category_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt1ActionPerformed

    private void category_txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_category_txt1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt1KeyReleased

    private void category_txt2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_category_txt2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt2FocusLost

    private void category_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt2ActionPerformed

    private void category_txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_category_txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt2KeyReleased

    private void category_txt3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_category_txt3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt3FocusLost

    private void category_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt3ActionPerformed

    private void category_txt3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_category_txt3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt3KeyReleased

    private void category_txt4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_category_txt4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt4FocusLost

    private void category_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt4ActionPerformed

    private void category_txt4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_category_txt4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_category_txt4KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cat_delete_btn;
    private javax.swing.JButton cat_save_btn;
    private javax.swing.JSpinner cat_search;
    private javax.swing.JButton cat_search_btn;
    private javax.swing.JButton cat_update_btn;
    private javax.swing.JTextField category_txt;
    private javax.swing.JTextField category_txt1;
    private javax.swing.JTextField category_txt2;
    private javax.swing.JTextField category_txt3;
    private javax.swing.JTextField category_txt4;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
