package pos.system;

import dao.CategoryDao;
import dao.DatabaseConnect;
import dao.ProductDao;
import model.Category;
import model.Product;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;

public class ManageProduct extends javax.swing.JPanel {

    /**
     * Creates new form Customer
     */

    public ManageProduct() {

        initComponents();
        addCategoryToComboBox();
        table_load();
        addPlaceholder(prod_name, "Enter product name");
        addPlaceholder(prod_price, "Enter product price");
        prod_save_btn.setEnabled(false);
        prod_delete_btn.setEnabled(false);
        prod_update_btn.setEnabled(false);
    }

    private void table_load() {
        DefaultTableModel dtm = (DefaultTableModel) prod_show_table.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.getAllRecords();
        for (Product productObj : list) {
            dtm.addRow(new Object[]{productObj.getId(), productObj.getName(), productObj.getCategory(), productObj.getPrice()});
        }
    }
    
    private void addCategoryToComboBox() {
        // Show all product data in table 
        
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while(itr.hasNext()) {
            Category categoryObj = itr.next();
            category.addItem(categoryObj.getName());
        }
    }
    

    public void validateField() {
        String name = prod_name.getText().trim();
        String price = prod_price.getText().trim();
        if (!name.isEmpty() && !price.isEmpty()) {
            prod_save_btn.setEnabled(true);
            prod_delete_btn.setEnabled(true);
            prod_update_btn.setEnabled(true);
        } else {
            prod_save_btn.setEnabled(false);
            prod_delete_btn.setEnabled(false);
            prod_update_btn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        prod_save_btn = new javax.swing.JButton();
        prod_update_btn = new javax.swing.JButton();
        prod_delete_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        prod_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        prod_price = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prod_show_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prod_search = new javax.swing.JSpinner();
        prod_search_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prod_search_table = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("Save");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        jPanel1.setPreferredSize(new java.awt.Dimension(451, 244));

        prod_save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/save.png"))); // NOI18N
        prod_save_btn.setText("Save");
        prod_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_save_btnActionPerformed(evt);
            }
        });

        prod_update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/update.png"))); // NOI18N
        prod_update_btn.setText("Update");
        prod_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_update_btnActionPerformed(evt);
            }
        });

        prod_delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/delete.png"))); // NOI18N
        prod_delete_btn.setText("Delete");
        prod_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_delete_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        prod_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prod_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_nameActionPerformed(evt);
            }
        });
        prod_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prod_nameKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add/Edit/Delete product info:");

        clearBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setPreferredSize(new java.awt.Dimension(92, 30));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Category:");

        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        prod_price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prod_price.setText(" ");
        prod_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_priceActionPerformed(evt);
            }
        });
        prod_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prod_priceKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(prod_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prod_update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prod_delete_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prod_price, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(59, 59, 59)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prod_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prod_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(prod_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prod_save_btn)
                    .addComponent(prod_update_btn)
                    .addComponent(prod_delete_btn)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 480, 230));

        prod_show_table.setBackground(new java.awt.Color(255, 204, 0));
        prod_show_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        prod_show_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Price"
            }
        ));
        prod_show_table.setRowHeight(23);
        prod_show_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prod_show_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prod_show_table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 549, 340));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        jPanel2.setPreferredSize(new java.awt.Dimension(463, 108));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search product info:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search By ID:");

        prod_search.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        prod_search.setToolTipText("Enter ID");
        prod_search.setBorder(null);

        prod_search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/search x30.png"))); // NOI18N
        prod_search_btn.setText("Search");
        prod_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(prod_search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(prod_search_btn)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prod_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod_search_btn))
                .addGap(15, 15, 15))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 480, -1));

        jPanel3.setBackground(new java.awt.Color(99, 43, 63));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Product Management");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Administration / Product Panel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(832, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search By Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        prod_search_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prod_search_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_search_tableActionPerformed(evt);
            }
        });
        prod_search_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prod_search_tableKeyReleased(evt);
            }
        });
        add(prod_search_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/background.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -20, 1400, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void search_data(String search) {

        // search customer table
        String name = prod_search_table.getText();

        try {

            DefaultTableModel dt = (DefaultTableModel) prod_show_table.getModel();
            dt.setRowCount(0);

            Statement s = DatabaseConnect.dbconn().createStatement();

            ResultSet result = s.executeQuery(" SELECT * FROM category WHERE category_name LIKE '%" + name + "%'");

            while (result.next()) {

                Vector v = new Vector();

                v.add(result.getString(1));
                v.add(result.getString(2));

                dt.addRow(v);
            }
        } catch (SQLException e) {

        }
    }


    private void prod_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_search_btnActionPerformed
        // search button function
        Product product = new Product();
        String id = prod_search.getValue().toString();
        product = ProductDao.searchRecord(id);
        if (category != null) {
            prod_name.setText(category.getName());
        }
        validateField();
    }//GEN-LAST:event_prod_search_btnActionPerformed

    // Custom method to add placeholder text when the JTextField is empty and loses focus
    private void addPlaceholder(javax.swing.JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(Color.GRAY);

        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                }
                textField.setForeground(Color.BLACK);
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(Color.GRAY);
                }
            }
        });
    }

    private void prod_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_nameActionPerformed

    }//GEN-LAST:event_prod_nameActionPerformed

    private void prod_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_save_btnActionPerformed
        // save customer data
        String productName = prod_name.getText();
        String productCategory = (String)category.getSelectedItem();
        String productPrice = prod_price.getText();
        
        try {
            Product product = ProductDao.checkRecord(productName, productCategory);
            if (product == null) {
                product = new Product();
                product.setName(productName);
                product.setCategory(productCategory);
                product.setPrice(productPrice);
                ProductDao.saveProduct(product);
            } else {
                ImageIcon icon = new ImageIcon("src/pos/system/img/delete.png");
                JOptionPane.showMessageDialog(null, "<html><b style=\"font-size: larger\">This product already exist!</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        table_load();
    }//GEN-LAST:event_prod_save_btnActionPerformed

    private void prod_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_update_btnActionPerformed
        // update customer data
        String product_id = prod_search.getValue().toString();
        String product_name = prod_name.getText();
        String product_category = (String)category.getSelectedItem();
        
        Product product = new Product();
        product.setId(product_id);
        product.setName(product_name);
        product.setCategory(product_category);
        try {
            ProductDao.updateProduct(product);
        } catch (SQLException ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        table_load();
    }//GEN-LAST:event_prod_update_btnActionPerformed

    private void prod_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_delete_btnActionPerformed
        // delete customer data
        Product product = new Product();
        String id = prod_search.getValue().toString();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Delete " + product.getName() + " product?", "Select", JOptionPane.YES_NO_OPTION);

        try {
            if (a == 0) {
                ProductDao.deleteProduct(id);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        table_load();
    }//GEN-LAST:event_prod_delete_btnActionPerformed

    private void prod_show_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prod_show_tableMouseClicked
        // mouse click and show data on textfield

        int index = prod_show_table.getSelectedRow();
        TableModel model = prod_show_table.getModel();
        String id = model.getValueAt(index, 0).toString();
        String name = model.getValueAt(index, 1).toString();
        String price = model.getValueAt(index, 3).toString();

        prod_search.setValue(Integer.valueOf(id));
        prod_name.setText(name);
        prod_price.setText(price);
        validateField();
    }//GEN-LAST:event_prod_show_tableMouseClicked

    private void prod_search_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prod_search_tableKeyReleased
        search_data(prod_search_table.getText());
    }//GEN-LAST:event_prod_search_tableKeyReleased

    private void prod_search_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_search_tableActionPerformed
        addPlaceholder(prod_search_table, "Enter name to search");
    }//GEN-LAST:event_prod_search_tableActionPerformed

    private void prod_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prod_nameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_prod_nameKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown


    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        setVisible(false);
        new ManageProduct().setVisible(true);
        validateField();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void prod_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prod_priceActionPerformed

    private void prod_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prod_priceKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_prod_priceKeyReleased

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_categoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> category;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton prod_delete_btn;
    private javax.swing.JTextField prod_name;
    private javax.swing.JTextField prod_price;
    private javax.swing.JButton prod_save_btn;
    private javax.swing.JSpinner prod_search;
    private javax.swing.JButton prod_search_btn;
    private javax.swing.JTextField prod_search_table;
    private javax.swing.JTable prod_show_table;
    private javax.swing.JButton prod_update_btn;
    // End of variables declaration//GEN-END:variables
}
