
package pos.system;

/**
 *
 * @author XU3N
 */
import javax.swing.JOptionPane;
import model.User;
import dao.UserDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class SignUp extends javax.swing.JFrame {
    
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";
    // declare user object for enter and validate data at sign up
    User tmp_user = new User();
    User verified_user = new User();
    User registered_user = null;
    /**
     * Creates new form SignUp
     */
    
    public SignUp() {
        initComponents();
        saveBtn.setEnabled(false);
        this.setExtendedState(SignUp.MAXIMIZED_BOTH);
        
    }
    
    public void clear() {
        user_name.setText("");
        user_email.setText("");
        user_tel.setText("");
        user_address.setText("");
        user_password.setText("");
        user_question.setText("");
        user_answer.setText("");
        saveBtn.setEnabled(false);
    }
    
    public void validateFields() {
        // set the user data
        tmp_user.setName(user_name.getText());
        tmp_user.setEmail(user_email.getText());
        tmp_user.setTelNo(user_tel.getText());
        tmp_user.setAddress(user_address.getText());
        tmp_user.setPassword(user_password.getText());
        tmp_user.setSecurityQuestion(user_question.getText());
        tmp_user.setAnswer(user_answer.getText());
        
        if (!tmp_user.getName().equals("") && tmp_user.getEmail().matches(emailPattern) && tmp_user.getTelNo().matches(mobileNumberPattern) && (tmp_user.getTelNo().length() == 10 || tmp_user.getTelNo().length() == 11) && !tmp_user.getPassword().equals("") && !tmp_user.getAddress().equals("") && !tmp_user.getSecurityQuestion().equals("") && !tmp_user.getAnswer().equals("")) 
        {
           saveBtn.setEnabled(true);
        }
        else 
        {
            saveBtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        user_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        user_tel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        user_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        user_password = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        user_question = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        user_answer = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        forgotBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("Sign up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        user_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user_name.setActionCommand("<Not Set>");
        user_name.setCaretColor(new java.awt.Color(0, 255, 204));
        user_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        user_name.setMinimumSize(new java.awt.Dimension(64, 23));
        user_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_nameFocusGained(evt);
            }
        });
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        user_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_nameKeyReleased(evt);
            }
        });
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 340, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        user_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user_email.setCaretColor(new java.awt.Color(0, 255, 204));
        user_email.setMinimumSize(new java.awt.Dimension(64, 23));
        user_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_emailFocusGained(evt);
            }
        });
        user_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_emailActionPerformed(evt);
            }
        });
        user_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_emailKeyReleased(evt);
            }
        });
        getContentPane().add(user_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 340, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile Number:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        user_tel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user_tel.setCaretColor(new java.awt.Color(0, 255, 204));
        user_tel.setMinimumSize(new java.awt.Dimension(64, 23));
        user_tel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_telFocusGained(evt);
            }
        });
        user_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_telActionPerformed(evt);
            }
        });
        user_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_telKeyReleased(evt);
            }
        });
        getContentPane().add(user_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 340, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        user_address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user_address.setCaretColor(new java.awt.Color(0, 255, 204));
        user_address.setMinimumSize(new java.awt.Dimension(64, 23));
        user_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_addressFocusGained(evt);
            }
        });
        user_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_addressActionPerformed(evt);
            }
        });
        user_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_addressKeyReleased(evt);
            }
        });
        getContentPane().add(user_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 340, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        user_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user_password.setCaretColor(new java.awt.Color(0, 255, 204));
        user_password.setMinimumSize(new java.awt.Dimension(64, 23));
        user_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_passwordFocusGained(evt);
            }
        });
        user_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_passwordActionPerformed(evt);
            }
        });
        user_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_passwordKeyReleased(evt);
            }
        });
        getContentPane().add(user_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 340, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Security Question:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        user_question.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user_question.setCaretColor(new java.awt.Color(0, 255, 204));
        user_question.setMinimumSize(new java.awt.Dimension(64, 23));
        user_question.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_questionFocusGained(evt);
            }
        });
        user_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_questionActionPerformed(evt);
            }
        });
        user_question.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_questionKeyReleased(evt);
            }
        });
        getContentPane().add(user_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 340, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Answer:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, -1, -1));

        user_answer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user_answer.setCaretColor(new java.awt.Color(0, 255, 204));
        user_answer.setMinimumSize(new java.awt.Dimension(64, 23));
        user_answer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_answerFocusGained(evt);
            }
        });
        user_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_answerActionPerformed(evt);
            }
        });
        user_answer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_answerKeyReleased(evt);
            }
        });
        getContentPane().add(user_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 340, -1));

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/save.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, -1, 40));

        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setPreferredSize(new java.awt.Dimension(92, 32));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 110, 40));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/logout.png"))); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, -1, 40));

        forgotBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        forgotBtn.setText("Forgot Password?");
        forgotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotBtnActionPerformed(evt);
            }
        });
        getContentPane().add(forgotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, -1, -1));

        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 660, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/img/crop-sportsman-running-dark (1).jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1600, 850));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    
    private void user_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_nameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameFocusGained

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed

    }//GEN-LAST:event_user_nameActionPerformed

    private void user_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_emailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_user_emailFocusGained

    private void user_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_emailActionPerformed

    private void user_telFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_telFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_user_telFocusGained

    private void user_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_telActionPerformed

    private void user_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_addressFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_user_addressFocusGained

    private void user_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_addressActionPerformed

    private void user_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_passwordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_user_passwordFocusGained

    private void user_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_passwordActionPerformed

    private void user_questionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_questionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_user_questionFocusGained

    private void user_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_questionActionPerformed

    private void user_answerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_answerFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_user_answerFocusGained

    private void user_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_answerActionPerformed

    private void forgotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ForgetPassword().setVisible(true);
    }//GEN-LAST:event_forgotBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you sure to Close The Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a==0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        registered_user = UserDao.checkEmailAndUsername(tmp_user.getEmail(), tmp_user.getName());
        if (!(registered_user == null) && registered_user.getStatus().equals("true") && (registered_user.getEmail().equals(tmp_user.getEmail()) || registered_user.getName().equals(tmp_user.getName()))) {
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:red\">Email or Username Already Taken!</b></html>", "Message", JOptionPane.ERROR_MESSAGE);
        } 
        else if(!(registered_user == null) && registered_user.getStatus().equals("false") && registered_user.getEmail().equals(tmp_user.getEmail()))
        {
            ImageIcon icon = new ImageIcon("src/pos/system/img/file.png");
            JOptionPane.showMessageDialog(null, "<html><b style=\"font-size: larger\">Please Wait For Admin Approval!</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
        }
        else 
        {
            verified_user = tmp_user;
            verified_user.setStatus("false");
            try {
                UserDao.saveData(verified_user);
                clear();
            } catch (SQLException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void user_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_nameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_user_nameKeyReleased

    private void user_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_emailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_user_emailKeyReleased

    private void user_telKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_telKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_user_telKeyReleased

    private void user_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_addressKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_user_addressKeyReleased

    private void user_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_passwordKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_user_passwordKeyReleased

    private void user_questionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_questionKeyReleased
        // TODO add your handling code here:.
        validateFields();
    }//GEN-LAST:event_user_questionKeyReleased

    private void user_answerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_answerKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_user_answerKeyReleased

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_loginBtnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton forgotBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField user_address;
    private javax.swing.JTextField user_answer;
    private javax.swing.JTextField user_email;
    private javax.swing.JTextField user_name;
    private javax.swing.JTextField user_password;
    private javax.swing.JTextField user_question;
    private javax.swing.JTextField user_tel;
    // End of variables declaration//GEN-END:variables
}
